/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_activetheoryinc_sdk_lib_BitGymCardio */

#ifndef _Included_com_activetheoryinc_sdk_lib_BitGymCardio
#define _Included_com_activetheoryinc_sdk_lib_BitGymCardio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_activetheoryinc_sdk_lib_BitGymCardio
 * Method:    BGUnityHasListener
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_activetheoryinc_sdk_lib_BitGymCardio_BGUnityHasListener
  (JNIEnv *, jclass);

/*
 * Class:     com_activetheoryinc_sdk_lib_BitGymCardio
 * Method:    BGInitCardio
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_activetheoryinc_sdk_lib_BitGymCardio_BGInitCardio
  (JNIEnv *, jclass, jstring, jint, jint);

JNIEXPORT void JNICALL Java_com_activetheoryinc_sdk_lib_BitGymCardio_BGCopyAndResizeVideoFrame(JNIEnv *env, jclass clazz, jbyteArray _greyscaleImage, jint inputWidth, jint inputHeight, jdouble timestamp, jint transform);


JNIEXPORT void JNICALL Java_com_activetheoryinc_sdk_lib_BitGymCardio_BGProcessVideoFrame (JNIEnv *, jclass);

/*
 * Class:     com_activetheoryinc_sdk_lib_BitGymCardio
 * Method:    BGInputVibration
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_activetheoryinc_sdk_lib_BitGymCardio_BGInputVibration
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     com_activetheoryinc_sdk_lib_BitGymCardio
 * Method:    BGGetExerciseReadingData
 * Signature: ()Lcom/activetheoryinc/sdk/lib/BGExerciseReadingData;
 */
JNIEXPORT jobject JNICALL Java_com_activetheoryinc_sdk_lib_BitGymCardio_BGGetExerciseReadingData
  (JNIEnv *, jclass);

/*
 * Class:     com_activetheoryinc_sdk_lib_BitGymCardio
 * Method:    BGSetExerciseMachineType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_activetheoryinc_sdk_lib_BitGymCardio_BGSetExerciseMachineType
  (JNIEnv *, jclass, jint);
/*
 * Class:     com_activetheoryinc_sdk_lib_BitGymCardio
 * Method:    BGSetDeviceOrientation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_activetheoryinc_sdk_lib_BitGymCardio_BGSetDeviceOrientation
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_activetheoryinc_sdk_lib_BitGymCardio
 * Method:    BGRenderToTexture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_activetheoryinc_sdk_lib_BitGymCardio_BGRenderToTexture
  (JNIEnv *, jclass);

/*
 * Class:     com_activetheoryinc_sdk_lib_BitGymCardio
 * Method:    BGStartFeedbackRender
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_activetheoryinc_sdk_lib_BitGymCardio_BGStartFeedbackRender
  (JNIEnv *, jclass, jint);

//void Java_com_activetheoryinc_sdk_lib_BitGymCardio_init(JNIEnv *_env, jobject _obj);

#ifdef __cplusplus
}
#endif
#endif
